services:
  msgcenter:
    image: ai_siem/msgcenter_image:1.0.0
    container_name: ai_siem_msgcenter
    build:
      context: ./MsgCenter
      dockerfile: dockerfile
      tags:
        - ai_siem/msgcenter_image:1.0.0
    # ports:
    #   - "10000:10000"
    networks:
      - ai_siem-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 100M

  agent:
    image: ai_siem/agent_image:1.0.0
    container_name: ai_siem_agent
    build:
      context: ./AIAgent
      dockerfile: dockerfile
      tags:
        - ai_siem/agent_image:1.0.0
    ports:
      - "10001:10001"
    volumes:
      - ./data:/app/logs
    networks:
      - ai_siem-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'      # Limit container to use max 20% of a CPU core
          memory: 100M     # Limit container to use max 100 megabytes of memory
          
  rpa:
    image: ai_siem/rpa_image:1.0.0
    container_name: ai_siem_rpa
    build:
      context: ./Rpa
      dockerfile: dockerfile
      tags:
        - ai_siem/rpa_image:1.0.0
    # ports:
    #   - "10002:10002"
    networks:
      - ai_siem-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M 

networks:
  ai_siem-network:
    driver: bridge
    name: ai_siem-network