apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-siem-service
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'

    spec:
      containers:
        - name: agent
          image: us-central1-docker.pkg.dev/testenv00/my-repo/agent_image:1.0.0
          ports:
            - name: http1
              containerPort: 10001
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
              
        - name: msgcenter
          image: us-central1-docker.pkg.dev/testenv00/my-repo/msgcenter_image:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"

        - name: rpa
          image: us-central1-docker.pkg.dev/testenv00/my-repo/rpa_image:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
  traffic:
  - percent: 100
    latestRevision: true


